### ISSUE TITLE
Execution failed for task ':compileDebugJava'. after upgrading Meteor to 1.2.0.1

### ISSUE THREAD

**Issue by solonm** [richsilv/cordova-notifications-demo#4]
**This is the error i get. Do you have any plans to update this for meteor 1.2.0.1**

Errors executing Cordova commands:
   While running Cordova app for platform Android with options --device:
   Error: Command failed: /meteor-meteoric-boilerplate/.meteor/local/cordova-build/platforms/android/cordova/run --device
   /meteor-meteoric-boilerplate/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find
   symbol
   webView.evaluateJavascript(js, null);
   ^
   symbol:   method evaluateJavascript(String,<null>)
   location: variable webView of type CordovaWebView
   /meteor-meteoric-boilerplate/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error: cannot find
   symbol
   webView.post(new Runnable(){
   ^
   symbol:   method post(<anonymous Runnable>)
   location: variable webView of type CordovaWebView
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use unchecked or unsafe operations.
   Note: Recompile with -Xlint:unchecked for details.
   2 errors
   FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileDebugJava'.
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  /meteor-meteoric-boilerplate/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
  throw e;
  ^
  Error code 1 for command: /meteor-meteoric-boilerplate/.meteor/local/cordova-build/platforms/android/gradlew with args:
  cdvBuildDebug,-b,/meteor-meteoric-boilerplate/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
  at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
  at ChildProcess.emit (events.js:98:17)
  at Process.ChildProcess._handle.onexit (child_process.js:820:12)
  ExitWithCode:1

Thank you,
Solonm

**Comment by timmakken** [comment]
Im experiencing the same issue here, it also took very long for initializing the first time with the new cordova requirement.
